#!/usr/bin/env python3
import os
import re
import subprocess
import sys
import yaml
import time

# Ensure script is run with sudo
if os.geteuid() != 0:
    print("[!] This script must be run with sudo/root privileges.")
    sys.exit(1)

RULES_PATH = "/etc/udev/rules.d/72-lte-modems.rules"
NETPLAN_PATH = "/etc/netplan/00-installer-config.yaml"

def get_udev_attr(iface, attr="devpath"):
    try:
        info = subprocess.check_output(["udevadm", "info", "-a", "-p", f"/sys/class/net/{iface}"], stderr=subprocess.DEVNULL).decode()
        m = re.search(fr'ATTRS{{{attr}}}==\s*"([^"]+)"', info)
        if m: return m.group(1)
    except:
        pass
    return None

def is_huawei_modem(iface):
    try:
        info = subprocess.check_output(["udevadm", "info", "-a", "-p", f"/sys/class/net/{iface}"], stderr=subprocess.DEVNULL).decode()
        if 'ATTRS{idVendor}=="12d1"' in info and 'ATTRS{idProduct}=="14db"' in info:
            return True
    except:
        pass
    return False

def get_interface_ip(iface):
    try:
        output = subprocess.check_output(["ip", "-4", "addr", "show", iface]).decode()
        m = re.search(r'inet\s+([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)', output)
        if m: return m.group(1)
    except:
        pass
    return None

def main():
    print("=== LTE Modem Multi-Route Config Engine (Professional PBR) ===")

    # 1. Pre-Discovery
    output = subprocess.check_output(["ip", "-br", "link"]).decode()
    all_ifaces = [line.split()[0] for line in output.splitlines() if line.split()[0] != "lo"]
    
    devpath_to_ip = {}
    devpath_to_current_name = {}
    
    for iface in all_ifaces:
        if is_huawei_modem(iface):
            subprocess.run(["ip", "link", "set", iface, "up"], check=False)
            dp = get_udev_attr(iface, "devpath")
            if not dp: continue
            
            devpath_to_current_name[dp] = iface
            ip = get_interface_ip(iface)
            if ip:
                devpath_to_ip[dp] = ip

    if not devpath_to_current_name:
        print("[!] No Huawei LTE modems detected.")
        sys.exit(0)

    # 2. Mapping Logic
    new_rules = {}
    assigned_names = set()
    
    for dp, ip in devpath_to_ip.items():
        try:
            octet = ip.split(".")[2]
            name = f"lte{octet}"
            new_rules[dp] = name
            assigned_names.add(name)
        except: pass

    next_id = 11
    for dp in sorted(devpath_to_current_name.keys()):
        if dp not in new_rules:
            while f"lte{next_id}" in assigned_names:
                next_id += 1
            name = f"lte{next_id}"
            new_rules[dp] = name
            assigned_names.add(name)

    # 3. Neutralization (Avoid collision)
    temp_map = {}
    for dp, current_name in devpath_to_current_name.items():
        dp_suffix = dp.split('.')[-1]
        temp_name = f"z_{dp_suffix}_{int(time.time()) % 100}"
        subprocess.run(["ip", "link", "set", current_name, "down"], check=False)
        subprocess.run(["ip", "link", "set", current_name, "name", temp_name], check=False)
        temp_map[dp] = temp_name

    # 4. Final Rename & Udev Rules
    with open(RULES_PATH, "w") as f:
        f.write("# Generated by auto_configure_modems.py\n")
        for dp, target_name in sorted(new_rules.items(), key=lambda x: int(re.sub(r'\D', '', x[1]))):
            f.write(f'SUBSYSTEM=="net", ACTION=="add", ATTRS{{idVendor}}=="12d1", ATTRS{{idProduct}}=="14db", ATTRS{{devpath}}=="{dp}", NAME="{target_name}"\n')
            
            z_name = temp_map.get(dp)
            if z_name:
                subprocess.run(["ip", "link", "set", z_name, "name", target_name], check=False)
                subprocess.run(["ip", "link", "set", target_name, "up"], check=False)

    subprocess.run(["udevadm", "control", "--reload-rules"], check=True)
    subprocess.run(["udevadm", "trigger"], check=True)

    # 5. Netplan Update with Policy-Based Routing (PBR)
    print("[*] Updating Netplan for Multi-Route PBR...")
    if os.path.exists(NETPLAN_PATH):
        with open(NETPLAN_PATH, "r") as f:
            config = yaml.safe_load(f) or {}
    else:
        config = {}

    if "network" not in config: config["network"] = {"version": 2, "renderer": "networkd", "ethernets": {}}
    ethernets = config["network"]["ethernets"]
    
    if "enp4s0" in ethernets:
        ethernets["enp4s0"]["dhcp4-overrides"] = {"route-metric": 200}
        ethernets["enp4s0"]["dhcp6-overrides"] = {"route-metric": 200}
    elif "enp37s0" in ethernets:
        ethernets["enp37s0"]["dhcp4-overrides"] = {"route-metric": 200}
        ethernets["enp37s0"]["dhcp6-overrides"] = {"route-metric": 200}

    # Clean old entries
    for name in list(ethernets.keys()):
        if name.startswith("lte"):
            del ethernets[name]

    # Add LTE interfaces with SOURCE-BASED ROUTING
    for dp, name in new_rules.items():
        try:
            octet = int(name.replace("lte", ""))
        except: octet = 150
        
        # PBR Logic: Traffic from this subnet goes to its own table
        metric = 100 + (octet - 11) * 10
        ethernets[name] = {
            "match": {"name": name},
            "dhcp4": True,
            "dhcp4-overrides": {"route-metric": metric},
            "dhcp-identifier": "duid",
            "optional": True,
            "routes": [
                {
                    "to": "default",
                    "via": f"192.168.{octet}.1",
                    "table": octet
                }
            ],
            "routing-policy": [
                {
                    "from": f"192.168.{octet}.0/24",
                    "table": octet
                }
            ]
        }

    with open(NETPLAN_PATH, "w") as f:
        yaml.dump(config, f, default_flow_style=False)

    try:
        subprocess.run(["netplan", "apply"], check=True, timeout=10)
        print("[✓] PBR Configuration Applied Successfully.")
    except Exception as e:
        print(f"[!] Netplan apply issues: {e}")

if __name__ == "__main__":
    main()
